# Линейная алгебра в _NumPy_

В библиотеках типа _NumPy_, либо каких-то еще есть встроенные модули, помогающие справляться с разного рода задачами. Мы уже рассматривали модуль **random** и **special** на предыдущем занятии. Теперь рассмотрим модуль **linalg** из библиотеки _NumPy_, в котором реализована вся линейная алгебра.

In [3]:
import numpy as np
from numpy.linalg import norm

## 1.1 Операции над векторами

### 1.1.1 Нормы

#### $\ell_{1}$ норма

$\ell_{1}$ норма 
(также известная как манхэттенское расстояние)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

In [4]:
a = np.array([1, 2, -3])
norm(a, ord=1)

6.0

#### $\ell_{2}$ норма

$\ell_{2}$ норма (также известная как евклидова норма)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

In [5]:
norm(a, ord=2)

3.7416573867739413

#### p-норма

p-норма для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
\left\Vert x \right\Vert_{p} = \left( \sum_{i=1}^n \left| x_{i} \right|^{p} \right)^{1 / p},~p \geq 1.
$$

### 1.1.2 Расстояния между векторами

Для двух векторов $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ и $y = (y_{1}, \dots, y_{n}) \in \mathbb{R}^{n}$ $\ell_{1}$ и $\ell_{2}$ раccтояния вычисляются по следующим формулам соответственно:

$$
 \rho_{1}\left( x, y \right) = \left\Vert x - y \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} - y_{i} \right|
$$

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} = 
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$

In [6]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])
print(norm(a - b, ord=1))
print(norm(a - b, ord=2))

17.0
12.12435565298214


#### Также можно через модуль cdist, но тогда минимальная размерность должна быть 2

In [7]:
from scipy.spatial.distance import cdist

In [8]:
a = a.reshape((1, 3))
b = b.reshape((1, 3))

In [9]:
cdist(a, b, metric='cityblock')

array([[17.]])

In [10]:
cdist(a,b, metric='euclidean')

array([[12.12435565]])

### 1.1.3 Скалярное произведение и угол между векторами

Скалярное произведение в пространстве $\mathbb{R}^{n}$ для двух векторов $x = (x_{1}, \dots, x_{n})$ и $y = (y_{1}, \dots, y_{n})$ определяется как:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$

In [11]:
a = np.array([0, 5, -1])
b = np.array([-4, 9, 3])
np.dot(a, b)

42

In [12]:
a.dot(b)

42

Длиной вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ называется квадратный корень из скалярного произведения, то есть длина равна евклидовой норме вектора:

$$
\left| x \right| = \sqrt{\langle x, x \rangle} = \sqrt{\sum_{i=1}^n x_{i}^2} =  \left\Vert x \right\Vert_{2}.
$$

Теперь, когда мы знаем расстояние между двумя ненулевыми векторами и их длины, мы можем вычислить угол между ними через скалярное произведение:

$$
\langle x, y \rangle = \left| x \right| | y | \cos(\alpha)
\implies \cos(\alpha) = \frac{\langle x, y \rangle}{\left| x \right| | y |},
$$

где $\alpha \in [0, \pi]$ — угол между векторами $x$ и $y$.

In [13]:
cos_angle = np.dot(a, b) / norm(a) / norm(b)
print(cos_angle)
print('Сам угол:', np.arccos(cos_angle))

0.8000362836474323
Сам угол: 0.6434406336093618


## 1.2 Операции над матрицами

### 1.2.1 Умножение матриц 

In [14]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)
print("Матрица a\n",a)
print("Матрица b\n",b)
print("Произведение\n",r1)

Матрица a
 [[1 0]
 [0 1]]
Матрица b
 [[4 1]
 [2 2]]
Произведение
 [[4 1]
 [2 2]]


In [15]:
c = np.array([1, 2])
r3 = b.dot(c)
print("Произведение матрицы на вектор:\n",r3)

Произведение матрицы на вектор:
 [6 6]


#### Покоординатное умножение!!

In [16]:
r = a * b
print(a)
print(b)
print(r)

[[1 0]
 [0 1]]
[[4 1]
 [2 2]]
[[4 0]
 [0 2]]


### 1.2.2 Транспонирование матриц

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### 1.2.3 Определитель матрицы

__Напоминание теории.__ Для квадратных матриц существует понятие __определителя__.

Например, для матрицы размера $2 \times 2$ получается:

$$\det \left( \begin{array}{cc} a_{11} & a_{12} \\ a_{21} & a_{22}  \end{array} \right) = a_{11} a_{22} - a_{12} a_{21}
$$

In [18]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)
print(det)

-1.0


### 1.2.4 Ранг матрицы

__Напоминание теории.__ __Рангом матрицы__ $A$ называется максимальное число линейно независимых строк (столбцов) этой матрицы.

In [19]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)
print(a)
print(r)

[[1 2 3]
 [1 1 1]
 [2 2 2]]
2


### 3.2.5 Системы линейных уравнений

In [20]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)
print("Решение системы X*a=b:\n",x)

Решение системы X*a=b:
 [2. 3.]


In [21]:
# убедимся в правильности
print(a.dot(x))

[9. 8.]


Бывают случаи, когда решение системы не существует. Но хотелось бы все равно "решить" такую систему. Логичным кажется искать такой вектор $x$, который минимизирует выражение $\left\Vert Ax - b\right\Vert^{2}$ — так мы приблизим выражение $Ax$ к $b$.

В `NumPy` такое псевдорешение можно искать с помощью функции __`numpy.linalg.lstsq(a, b, ...)`__, где первые два аргумента такие же, как и для функции __`numpy.linalg.solve()`__. 
Помимо решения функция возвращает еще три значения, которые нам сейчас не понадобятся.

In [22]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(a, b)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [23]:
print("Псевдорешение системы:\n", x)

Псевдорешение системы:
 [ 1.   -0.95]


### 1.2.6 Обращение матриц

__Напоминание теории.__  Для квадратных невырожденных матриц определено понятие __обратной__ матрицы. 

Пусть $A$ — квадратная невырожденная матрица. Матрица $A^{-1}$ называется __обратной матрицей__ к $A$, если 

$$AA^{-1} = A^{-1}A = I,
$$ 

где $I$ — единичная матрица.

В `NumPy` обратные матрицы вычисляются с помощью функции __`numpy.linalg.inv(a)`__, где __`a`__ — исходная матрица.

In [24]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)
print(a)
print(b)

[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]


In [25]:
# произведение на обратную должно дать единичную матрицу
a.dot(b)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

### 1.2.7 Собственные числа и собственные вектора матрицы

__Напоминание теории.__ Для квадратных матриц определены понятия __собственного вектора__ и __собственного числа__.

Пусть $A$ — квадратная матрица и $A \in \mathbb{R}^{n \times n}$. __Собственным вектором__ матрицы $A$ называется такой ненулевой вектор $x \in \mathbb{R}^{n}$, что для некоторого $\lambda \in \mathbb{R}$ выполняется равенство $Ax = \lambda x$. При этом $\lambda$ называется __собственным числом__ матрицы $A$. 

В `NumPy` собственные числа и собственные векторы матрицы вычисляются с помощью функции __`numpy.linalg.eig(a)`__, где __`a`__ — исходная матрица. В качестве результата эта функция выдает одномерный массив __`w`__ собственных чисел и двумерный массив __`v`__, в котором по столбцам записаны собственные вектора, так что вектор __`v[:, i]`__ соотвествует собственному числу __`w[i]`__.

In [26]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print("Матрица A:\n", a)
print("Собственные числа:\n", w)
print("Собственные векторы:\n", v)

Матрица A:
 [[-1 -6]
 [ 2  6]]
Собственные числа:
 [2. 3.]
Собственные векторы:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


Таким образом, мы вспомнили основные понятия линейной алгебры и посмотрели, как легко это можно реализовать на компьютере. А теперь вперед в тропические леса к _Pandas_! 